import numpy as np;
arr_1D=np.arange(0,9,1).reshape(1,9);
arr_1D=arr_1D.ravel();
print(arr_1D);
print("--------------------------------append 1D, make 1D---------------------------------------");
arr_1D=np.append(arr_1D,[9,10,11,12],axis=0);
print(arr_1D);
print("-----------------------------------------------------------------------");
arr_2D=np.arange(0,20,1).reshape(4,5);
print(arr_2D);
print("--------------------------------append 2D, make 2D, axis-0---------------------------------------");
arr_2D=np.append(arr_2D,[[20,21,22,23,24]],axis=0);
print(arr_2D);
print("--------------------------------append 2D, make 2D, axis-1---------------------------------------");
arr_2D=np.append(arr_2D,[[30],[31],[32],[33],[34]],axis=1);
print(arr_2D);
print("--------------------------------append 3D, make 3D, axis-0---------------------------------------");
arr_3D=np.arange(0,18,1).reshape(2,3,3);
print("Original:\n",arr_3D);
arr_3D_sample=np.arange(18,27,1).reshape(3,3);
arr_3D=np.append(arr_3D,[arr_3D_sample],axis=0);
print("resultant_3D_axis_zero:\n",arr_3D);
print("--------------------------------append 3D, make 3D, axis-1---------------------------------------");
arr_2D_combine=np.arange(100,190,10).reshape(3,3);
arr_3D=np.append(arr_3D,arr_2D_combine[:,np.newaxis,:],axis=1);
print("append_axis_one:\n",arr_3D);
print("--------------------------------append 3D, make 3D, axis-2---------------------------------------");
arr_2D_combine_axis_two=np.arange(1000,2200,100).reshape(3,4);
arr_3D=np.append(arr_3D,arr_2D_combine_axis_two[:, :, np.newaxis],axis=2);
print(arr_3D);

